// 全局引入变量
import '@/packages/theme-chalk/variables.scss'
import '@/packages/components/layout/style/aside.scss';
import '@/packages/components/layout/style/container.scss';
import '@/packages/components/layout/style/footer.scss';
import '@/packages/components/layout/style/header.scss';
import '@/packages/components/layout/style/main.scss';
import '@/packages/components/icon/style/icon.scss';
import '@/packages/components/grid/style/col.scss';
import '@/packages/components/grid/style/row.scss';
import '@/packages/components/button/style/button.scss';
import '@/packages/components/link/style/link.scss';
import '@/packages/components/space/style/space.scss';
import '@/packages/components/divider/style/divider.scss';
import '@/packages/components/ellipsis/style/ellipsis.scss';
import '@/packages/components/sticky/style/sticky.scss';
import '@/packages/components/anchor/style/anchor.scss';
import '@/packages/components/anchor/style/anchor-link.scss';
import '@/packages/components/anchor/style/anchor-point.scss';
import '@/packages/components/backtop/style/backtop.scss';
import '@/packages/components/scroll/style/scroll.scss';
import '@/packages/components/breadcrumb/style/breadcrumb.scss';
import '@/packages/components/breadcrumb/style/breadcrumb-item.scss';
import '@/packages/components/loading-bar/style/loading-bar.scss';
import '@/packages/components/page-header/style/page-header.scss';
import '@/packages/components/steps/style/steps.scss';
import '@/packages/components/steps/style/step.scss';