// 全局引入变量
import '@/packages/theme-chalk/variables.scss'
import '@/packages/components/layout/style/aside.scss';
import '@/packages/components/layout/style/container.scss';
import '@/packages/components/layout/style/footer.scss';
import '@/packages/components/layout/style/header.scss';
import '@/packages/components/layout/style/main.scss';
import '@/packages/components/icon/style/icon.scss';
import '@/packages/components/grid/style/col.scss';
import '@/packages/components/grid/style/row.scss';
import '@/packages/components/button/style/button.scss';
import '@/packages/components/link/style/link.scss';
import '@/packages/components/space/style/space.scss';
import '@/packages/components/divider/style/divider.scss';
import '@/packages/components/ellipsis/style/ellipsis.scss';